# This config includes all necessary dataset paths and settings related to MedST-28 dataset

dataset:
  path_to_dataset: "dataset/MedST28_dataset"                     # path to folder containing dataset
  path_to_stats:   "dataset/MedST28_dataset/MedSt28_stats.json"  # path to MedST-28 dataset stats (used for normalization)
  data_extension:           ".nc"                                                # pre-define dataset files extension
  time_steps:               "10"                                                # use "max" to use all available time_steps from sample or specify
  samples_patch_size:       "64"                                                 # use max to select the max patch size (for MedSt28 is 64x64) or specify a smaller patch size
  include_variables:                                                             # specify variables to include from netCDF files
                            #- burned_areas
                            - d2m
                            - ignition_points
                            - lai
                            - lst_day
                            - lst_night
                            - ndvi
                            - rh
                            - smi
                            - sp
                            - ssrd
                            - t2m
                            - tp
                            - u
                            - v
                            - aspect
                            - curvature
                            - dem
                            - roads_distance
                            - slope
                            - lc_agriculture
                            - lc_forest
                            - lc_grassland
                            - lc_settlement
                            - lc_shrubland
                            - lc_sparse_vegetation
                            - lc_water_bodies
                            - lc_wetland
                            - population                     

  train:
    include_years:          "all"            # include data from years, if set to "all" all available years are included except those specified in validation and test sets (2006-2020)
    include_months:         "all"            # include data from months, if set to "all" all available months are included  | "5, 6, 7, 8, 9"
    
  validation:  
    include_years:          "2021"         
    include_months:         "all"     

  test:  
    include_years:          "2022"         
    include_months:         "all"     
    
  reference_date:           "2000-01-01"    # reference day to get temporal encoding (Year, Month, Day)