# config for pre-train

pre-train:
  # save path for checkpoints or models
  checkpoint_save_path:   "output/pre_train_MedST-28_50M_checkpoints"  # path to folder for saving checkpoints
  visualize_results_path: "output/pre-train_MedST28_50M_results"       # path to save results for visualize pre-train results script

  # pre-train settings
  num_of_epochs:      "300"     # max number of epochs (using 2 for testing)
  batch_size:         "64"      # default 64
  learning_rate:      "1e-4"  # change later # TODO: rename this into max_learning_rate
  mask_ratio:         "0.75"    # default 75 %

  # model h-parameters for ViT Encoder
  patch_size:         "4"      # define a patch size for ViT backbone
  embed_dim:          "512"    # default value = 1024
  depth:              "16"      # default value = 24
  num_heads:          "16"     # default value = 16

  # model h-parameters for ViT Decoder
  decoder_embed_dim:  "256"    # default value = 512
  decoder_depth:      "4"      # default value = 8
  decoder_num_heads:  "8"     # default value = 16

  # additional settings
  mlp_ratio:          "4"      # default value = 4, may be replaced with actual mlp size
  norm_pixel_loss:    "False"  # default value = False
